apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster-producer-tests
  namespace: kafka
  labels:
    app: kafka-load-tests
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-load-tests
  template:
    metadata:
      labels:
        name: kafka-load-tests
    spec:
      containers:
        - name: kafka-perf-test
          image: rishabh96b/kafka-workload:2.4.1
          imagePullPolicy: Always
          command:
            - /opt/kafka/run_producer_test.sh
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka-instance-svc:9093"
            - name: NUM_TOPICS
              value: "30"
            - name: TEST_INTERVAL_SECONDS
              value: "5"
            - name: PRODUCER_THROUGHPUT
              value: "10"
            - name: NUM_RECORDS
              value: "10"
            - name: RECORD_SIZE
              value: "50"
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster-consumer-tests
  namespace: kafka-mwt
  labels:
    app: kafka-load-tests
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-load-tests
  template:
    metadata:
      labels:
        name: kafka-load-tests
    spec:
      containers:
        - name: kafka-perf-test
          image: rishabh96b/kafka-workload:2.4.1
          imagePullPolicy: Always
          command:
            - /opt/kafka/run_consumer_test.sh
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka-instance-svc:9093"
            - name: NUM_TOPICS
              value: "30"
            - name: NUM_RECORDS
              value: "1000"
            - name: TEST_INTERVAL_SECONDS
              value: "1"
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
  strategy:
    type: Recreate
